### ISSUE TITLE
Commit message regex linter

### ISSUE THREAD

**Issue by tomphp** [PurpleBooth/git-mit#119]
Something like

```
git mit-config lint enable commit-message-regex '/^(Added|Updated|Fixed|Removed): /'
```

**Comment by PurpleBooth** [comment]
I am not sure about this. I think part of what I want to do with this nudge people towards good practices.

So I would be up for a series of lints on [Conventional Changelog](https://github.com/conventional-changelog/conventional-changelog) or some similar system.
