### ISSUE TITLE
Commands to manage you authors file

### ISSUE THREAD

**Issue by tomphp** [PurpleBooth/git-mit#204]
e.g.

`git mit-authors add jd --name "Jane Doe" --email "jd@example.com"`

`git mit-authors remove to`

`git mit-authors update to --email "new@example.com"`

`git mit-authors list`

**Comment by PurpleBooth** [comment]
This is tricky because the file isn't always a file, it's sometimes a command, for example mine is

```shell
CLOUDSDK_ACTIVE_CONFIG_NAME="secret-store" sops -d /Users/billiethompson/.config/git-mit/authors.yml
```

Having said this, this is a feature I really want. So I might see if I can make it work

**Comment by PurpleBooth** [comment]
Ok, so two parts to this

* Create a command that lets you add repository-specific authors in the git config.
* Create a command that prints out the currently available authors

This should be enough for anyone to bridge the gap with their own scripts.
