### ISSUE TITLE
Errors in the authors file are not very easy to debug

### ISSUE THREAD

**Issue by tomphp** [PurpleBooth/git-mit#307]
I got the following error due to missing `"`s in the TOML file.

`Error: AuthorYaml(Parse(Scan(ScanError { mark: Marker { index: 5, line: 2, col: 0 }, info: "did not find expected <document start>" }), Error { inner: ErrorInner { kind: Wanted { expected: "newline", found: "a period" }, line: Some(2), col: 11, at: Some(32), message: "", key: [] } }))`

It's confusing not least because it says `AuthorYaml` when the error is in a `.toml` file. I was trying to find a conflicting `.yaml` file somewhere.

**Comment by PurpleBooth** [comment]
Wow! That's a shitty error!

It should support both Yaml and Toml, but the error should totally reflect the right one. I don't suppose you have an example I can use in the tests?

**Comment by PurpleBooth** [comment]
```
Unable to parse the author config

You can fix this by correcting the file so it's parsable

You can see a parsable example by running:
git mit-config mit example

Here's the technical details, that might help you track down the source of the problem

failed to parse authors as toml invalid type: string "Hello, I am a broken file", expected a map at line 1 column 1 or as yaml expected an equals, found a comma at line 1 column 6
```

This will now output
