### ISSUE TITLE
GitHub seems to want the Co-authored-by trailer at the end of the message

### ISSUE THREAD

**Issue by tomphp** [PurpleBooth/git-mit#308]
GitHub is not showing the pairing partner avatar on commits which use relates-to. Comparing messages which do show 2 avatars with ones that don't, I think it's down to the fact that `Relates-to:` appears after `Co-authored-by:`.

## Examples

This shows 2 avatars on Github:

```
Add Payment to the module

[#12312312]

Co-authored-by: Txx Lxxx <txx.lxxx@example.com>
```

This does not:

```
Extract payment notification handling into class

Co-authored-by: Txx Lxxx <txx.lxxx@example.com>

Relates-to: [#12312312]
```

**Comment by PurpleBooth** [comment]
Can you confirm it's not related to the space between the trailers? The latest version should put them together.

**Comment by PurpleBooth** [comment]
Looks like with the latest version we insert the trailers in the correct place so this doesn't happen.

![grafik](https://user-images.githubusercontent.com/133327/87240909-fdd65800-c41d-11ea-8eaf-c950f7291c7c.png)
![grafik](https://user-images.githubusercontent.com/133327/87240914-0890ed00-c41e-11ea-95d0-e3d6dccf6eda.png)
