### ISSUE TITLE
Running git-mit outside a repository directory causes unusual behaviour

### ISSUE THREAD

**Issue by PurpleBooth** [PurpleBooth/git-mit#397]
Currently if you run git-mit outside the project directory, it will write to the users configuration.

This leads to a confusing situation where the configuration can fail to change or other weird behaviour. I can't think of any reason that we'd want to write to anything other than the local configuration.

To fix this change how we load the repository never to use anything other than the repository directly.

**Comment by mattwynne** [comment]
Ho ho I think this was what happened to me, I was making commits as one of my co-workers for ages until I realised what was going on.

**Comment by PurpleBooth** [comment]
Yeah, sorry about that. I think what I'd like to do is to prevent it from storing the user config in the global location ever, or at least print a warning to stderr.

It's on the todo list but I've been distracted by another project.

**Comment by mattwynne** [comment]
Good to see you're still working on this Billie!
