### ISSUE TITLE
Newlines in my commit trailer

### ISSUE THREAD

**Issue by mattwynne** [PurpleBooth/git-mit#413]
Hello! Thanks for this lovely tool.

I'm getting newlines inserted between my co-author trailers:

<img width="756" alt="Screenshot 2020-09-29 at 11 28 16" src="https://user-images.githubusercontent.com/19260/94547265-f5383580-0246-11eb-8359-ad1b06040281.png">

Any idea why, or how to debug it?

**Comment by mattwynne** [comment]
I'm using a toml config file, in `~/.config/git-mit/mit.toml`

**Comment by PurpleBooth** [comment]
In previous versions, I was seeing this behaviour but I thought I'd fixed it gotten it. Can you provide a copy of the commit message, I'll try and replicate it and track down the problem.

I suppose it might be worth checking the version you're running, you can get that running `git-mit --version`?

Thanks!

**Comment by mattwynne** [comment]
Ah! I was using version 3.55.0; upgrading to 3.98.22 has fixed it. Sorry for the noise!

**Comment by PurpleBooth** [comment]
No problem, it's nice to know I am not the only one who uses this, to be honest 😄
