### ISSUE TITLE
`git mit-install` message error

### ISSUE THREAD

**Issue by evensolberg** [PurpleBooth/git-mit#637]
**Describe the bug**
When running `git mit-install`, the package outputs a bunch of help information, ending with

```
...
        The authors and issue number appear on the commit. These authors are saved into your current repository for ad-hoc pairing. When you're ready make the authors everywhere run
        
        mkdir -p "$HOME/.config/git-mit"
        git mit-config generate > "$HOME/.config/git-mit/mit.toml"
```

This should actually be

```
...

        git mit-config mit generate >  "$HOME/.config/git-mit/mit.toml"
```

The `mit` part is missing.

**Comment by PurpleBooth** [comment]
Thanks for this bug report, this is the sort of stuff that makes a big difference to new users, and I would have never noticed it without your report
