### ISSUE TITLE
Set the current Pivitol Tracker ticket number

### ISSUE THREAD

**Issue by tomphp** [PurpleBooth/git-mit#93]
Something like `git hooks current-story #123123` and all commits will have it added until a new story id is added.

**Comment by PurpleBooth** [comment]
Would this timeout like the authors?

**Comment by tomphp** [comment]
I think that would be great!

**Comment by PurpleBooth** [comment]
I wonder if we can make it very generic like, we add a new trailer, something like

```
Realign the jangles

The Jangles are out of date and need realigning. This will bring them up to modern influx standards.

Relates-to: JRA-123
```


```
Realign the jangles

The Jangles are out of date and need realigning. This will bring them up to modern influx standards.

Relates-to: [#123456789]
```

Then people can set whatever they want in there
